### ISSUE TITLE
Is `serde` support possible?

### ISSUE THREAD

**Issue by n3vu0r** [sgodwincs/ordered-multimap-rs#9]
It would be nice to have `ListOrderedMultimap<Key, Table>` over `IndexMap<Key, Vec<Table>>` for TOML deserialisation. In this way, arrays of tables `[[key]]` would preserve order even along different keys as they are no longer grouped by them.

**Comment by sgodwincs** [comment]
I'd be willing to support serde behind a configuration flag. Unfortunately, I'm a bit busy at the moment, but if you want to give it a shot I'd be willing to accept a PR. Otherwise, it will take a bit longer for me to get around to this.

**Comment by n3vu0r** [comment]
Great. I'm also busy currently, but I will let you know before I try something.
